version: "3"

services:
  mopidy:
    privileged: true
    image: localhost/mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - './mopidy/cache_dir/:/home/mopidy/.cache/'
      - './mopidy/config_dir/:/home/mopidy/.config/mopidy/'
      - './mopidy.conf:/home/mopidy/.config/mopidy/mopidy.conf'
      - './mopidy/data_dir/:/home/mopidy/.local/share/mopidy/'
      - '/media/paul/Data/Paul/Music:/media/paul/Data/Paul/Music'
    restart: unless-stopped
    devices:
      - "/dev/snd"
